= Vintage Computing Books

This file is list of the books in my private library regarding vintage
computing, vintage computer architecture, and some Unix history. It
happens regularly, that I found a book interesting on eBay, but am not
sure, if it sits already on some shelf or not. So this list is written
and updated primarily for myself.

Books can happen to be listed more then once, because they fit into
more than one category. Numbers in format *Bk??* refer to the storage
location of the book.


== About Companies

_Donald M. Hall_ +
*Generation of Wealth -- The rise of Control Data and how it inspired
an era of innovation and investment in the Upper Midwest* +
2004 +
controldata cdc +

_Robert M. Price_ + 
*The Eye for Innovation -- Recognizing Possibilities and Managing the
Creative Enterprise* + 
Yale University Press, New Heaven, London; 2005 + 
controldata cdc + 


== About People

/James C. Worthy/\\
*William C. Norris -- Portrait of a Maverick*\\
1987\\
/1911-2006; Founder and CEO of Control Data Corp./
controldata cdc norris


== Computer Architecture


## Processor Architecture ##

*Michael J. Flynn*
**Computer Architecture -- Pipelined And Parallel Processor Design**
Jones and Bartlett Publishers, Inc.; 1995
computerarchitecture pipelining




## Storage and I/O Subsystems ##


**Alles über Storage und Backup**
Linux Magazin Technical Review 03; 2007.
linux storage

*Günter Born*
**Referenzhandbuch Dateiformate -- Grafik, Text, Datenbanken,
*Tabellenkalkulation**
Addison-Wesley Publishing Company; 1991.
fileformat dateiformat
Bk01



## Protocols and Communication ##

*Hartmut Hermes*
**Datenaustausch mit EDIFACT -- Produktstammdaten DIN 16561-22 -- Anwendungshandbuch für Handel und Industrie**
Beuth Verlag GmbH, Berlin, Wien, Zürich; 1. Auflage; 1998.
edifact


## Operating Systems ##

**Solaris White Album**
July 2004.
solaris sun unix


*Rolf Dietze, Tatjana Heuser, Jörg Schilling*
**OpenSolaris für Anwender, Administratoren und Rechenzentren**
Springer-Verlag Berlin Heidelberg; 2006.
This is the first OpenSolaris book in German and one of the first
*OpenSolaris books worldwide written outside from Sun.
opensolaris solaris sun unix
Bk01

*Nicholas A. Solter, Gerald Jelinek, David Miner*
**OpenSolaris Bible**
Wiley Publishing Inc.; 2009.
opensolaris solaris sun unix
Bk01

*Jürgen Gulbins*
**Unix -- Eine Einführung in UNIX, seine Begriffe und seine
*Kommandos**
Springer-Verlag Berlin Heidelberg New York Tokyo; 1984.
unix
Bk01

*Arnold Robbins*
**Unix in a Nutshell -- Für SVR4 und Solaris 7**
O'Reilly Verlag GmbH & Co. KG; 3rd ed.; 2000
unix solaris
Bk01



## Software Engineering and Programming ##

